const statesData = [
	{ name: "Select a state ", label: "Select a state " },
	{ name: "Alabama", label: "AL" },
	{ name: "Alaska", label: "AK" },
	{ name: "American Samoa", label: "AS" },
	{ name: "Arizona", label: "AZ" },
	{ name: "Arkansas", label: "AR" },
	{ name: "California", label: "CA" },
	{ name: "Colorado", label: "CO" },
	{ name: "Connecticut", label: "CT" },
	{ name: "Delaware", label: "DE" },
	{ name: "District Of Columbia", label: "DC" },
	{ name: "Federated States Of Micronesia", label: "FM" },
	{ name: "Florida", label: "FL" },
	{ name: "Georgia", label: "GA" },
	{ name: "Guam", label: "GU" },
	{ name: "Hawaii", label: "HI" },
	{ name: "Idaho", label: "ID" },
	{ name: "Illinois", label: "IL" },
	{ name: "Indiana", label: "IN" },
	{ name: "Iowa", label: "IA" },
	{ name: "Kansas", label: "KS" },
	{ name: "Kentucky", label: "KY" },
	{ name: "Louisiana", label: "LA" },
	{ name: "Maine", label: "ME" },
	{ name: "Marshall Islands", label: "MH" },
	{ name: "Maryland", label: "MD" },
	{ name: "Massachusetts", label: "MA" },
	{ name: "Michigan", label: "MI" },
	{ name: "Minnesota", label: "MN" },
	{ name: "Mississippi", label: "MS" },
	{ name: "Missouri", label: "MO" },
	{ name: "Montana", label: "MT" },
	{ name: "Nebraska", label: "NE" },
	{ name: "Nevada", label: "NV" },
	{ name: "New Hampshire", label: "NH" },
	{ name: "New Jersey", label: "NJ" },
	{ name: "New Mexico", label: "NM" },
	{ name: "New York", label: "NY" },
	{ name: "North Carolina", label: "NC" },
	{ name: "North Dakota", label: "ND" },
	{ name: "Northern Mariana Islands", label: "MP" },
	{ name: "Ohio", label: "OH" },
	{ name: "Oklahoma", label: "OK" },
	{ name: "Oregon", label: "OR" },
	{ name: "Palau", label: "PW" },
	{ name: "Pennsylvania", label: "PA" },
	{ name: "Puerto Rico", label: "PR" },
	{ name: "Rhode Island", label: "RI" },
	{ name: "South Carolina", label: "SC" },
	{ name: "South Dakota", label: "SD" },
	{ name: "Tennessee", label: "TN" },
	{ name: "Texas", label: "TX" },
	{ name: "Utah", label: "UT" },
	{ name: "Vermont", label: "VT" },
	{ name: "Virgin Islands", label: "VI" },
	{ name: "Virginia", label: "VA" },
	{ name: "Washington", label: "WA" },
	{ name: "West Virginia", label: "WV" },
	{ name: "Wisconsin", label: "WI" },
	{ name: "Wyoming", label: "WY" },
];
export default statesData;
